name: PR Check
on:
  pull_request:
    types: [
      'opened',
      'synchronize',
      ]

jobs:
  build:
    runs-on: ubuntu-latest 
    permissions:
      packages: read 
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          scope: '@bullrich'
      - run: cat $NPM_CONFIG_USERCONFIG
      - run: npm install --save @bullrich/action-test
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: execute code
        run: npm start
        working-directory: node_modules/@bullrich/action-test
